# Project Cycle 2 - Group 5 - 01 Data Check
## 1. Research Question
1. Is the proportion of students who feel sad or hopeless different from 0.30?

2. Is the mean BMI percentile different from 65?

Additional EDA exploration:

3. Do students with higher BMI percentile tend to report feeling sad or hopeless more often?

## 2. Variable Definition
### 2-1 SadOrHopeless
- Variable name: SadOrHopeless
- Meaning: Whether the student felt sad or hopeless
- Valid codes:
  - 1 = Yes
  - 2 = No
- Success definition:
  - success = code 1
  - failure = code 2
- Benchmark for one-sample proportion test:
  - p0 = 0.30

### 2-2 BMIPCT
- Variable name: BMIPCT
- Meaning: BMI percentile
- Benchmark for one-sample mean test:
  - μ0 = 65

## 3. Import Libraries

In [13]:
import pandas as pd
import numpy as np

## 4. Load Dataset

In [14]:
df = pd.read_csv("../data/raw/YRBS_2007.csv")
df.head()

,RaceEth,HowOldAreYou,WhatIsYourSex,InWhatGradeAreYou,AreYouHispanicOrLatino,WhatIsYourRace,HowTallAreYouWithoutShoesInMeters,HowMuchDoYouWeighWithoutShoesInKG,BicyleHelmetUse,SeatBeltUse,...,InjuredWhileExercising,HIVTesting,SunscreenUse,SunProtection,Sleep,HealthInGeneral,BMIPCT,weight,stratum,psu
0,7.0,4.0,2.0,2.0,1.0,C,NaN,NaN,2.0,1.0,...,3.0,2.0,1.0,1.0,5.0,3.0,NaN,1.5104,101,11030
1,5.0,7.0,2.0,2.0,2.0,E,1.70,68.04,4.0,4.0,...,2.0,3.0,1.0,5.0,4.0,3.0,66.531824,1.8559,101,11030
2,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,5.0,3.0,...,2.0,3.0,2.0,1.0,1.0,1.0,NaN,1.8559,101,11030
3,7.0,1.0,1.0,1.0,1.0,A,1.63,79.38,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,98.174319,1.3264,101,11030
4,7.0,1.0,1.0,5.0,1.0,B,NaN,NaN,6.0,5.0,...,NaN,1.0,NaN,NaN,NaN,NaN,NaN,1.3264,101,11030

The dataset was successfully loaded. The first few rows show the structure of the data, including the variables SadOrHopeless and BMIPCT, which will be used in this analysis.

## 5. Dataset Overview
### 5-1 Dataset Dimensions

In [15]:
df.shape

(14041, 103)

The dataset contains a certain number of rows (observations) and columns (variables). This provides an overview of the dataset size and helps us understand how much data is available for analysis.

### 5-2 Data Structure and Variable Types

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14041 entries, 0 to 14040
Columns: 103 entries, RaceEth to psu
dtypes: float64(100), int64(2), object(1)
memory usage: 11.0+ MB

The dataset includes multiple variables with different data types. We can also identify missing values in each column. This step helps verify whether the variables SadOrHopeless and BMIPCT are in the correct format for analysis.

### 5-3 Preview of Key Variables

In [17]:
df[["SadOrHopeless", "BMIPCT"]].head(10)

   SadOrHopeless     BMIPCT
0            1.0        NaN
1            2.0  66.531824
2            1.0        NaN
3            1.0  98.174319
4            1.0        NaN
5            2.0  33.075531
6            2.0  45.688334
7            2.0  62.390331
8            2.0  13.969642
9            2.0  80.358795

The preview shows the first few observations of SadOrHopeless and BMIPCT. This helps us understand how the data is recorded and whether there are any obvious issues such as invalid values or missing entries.

## 6. Distribution of SadOrHopeless

In [18]:
df["SadOrHopeless"].value_counts(dropna=False).sort_index()

SadOrHopeless
1.0    4153
2.0    9692
NaN     196
Name: count, dtype: int64

This step checks whether the valid codes (1 and 2) are present and identifies any invalid or missing values. This ensures that the data meets the assumptions for further analysis.

## 7. Missing Value Check

In [19]:
df["SadOrHopeless"].isna().sum()
df["BMIPCT"].isna().sum()

979

Missing values are identified and will be handled in the data cleaning step.

## 8. Data Cleaning and Recoding: SadOrHopeless

In [ ]:
sad_df = df[["SadOrHopeless"]].copy()   
sad_df = sad_df[sad_df["SadOrHopeless"].isin([1, 2])]
sad_df["Sad_binary"] = sad_df["SadOrHopeless"].map({1: 1, 2: 0})

sad_df[["SadOrHopeless", "Sad_binary"]].head()

   SadOrHopeless  Sad_binary
0            1.0           1
1            2.0           0
2            1.0           1
3            1.0           1
4            1.0           1

Only valid responses (codes 1 and 2) are retained for SadOrHopeless. The variable is recoded into a binary format, where 1 represents "Yes" (feeling sad or hopeless) and 0 represents "No". This binary variable will be used in the proportion analysis.

## 9. Data Cleaning: BMIPCT

In [21]:
bmi_df = df[["BMIPCT"]].dropna().copy()
bmi_df.head()

      BMIPCT
1  66.531824
3  98.174319
5  33.075531
6  45.688334
7  62.390331

Missing values in BMIPCT are removed to ensure that the mean analysis is based only on valid observations. The cleaned dataset will be used for calculating the sample mean and conducting inference.

## 10. Joint Dataset
### 10-1 Prepare Dataset for Joint Analysis

In [22]:
joint_df = df[["SadOrHopeless", "BMIPCT"]].copy()
joint_df = joint_df[joint_df["SadOrHopeless"].isin([1, 2])]
joint_df = joint_df.dropna(subset=["BMIPCT"])
joint_df["Sad_binary"] = joint_df["SadOrHopeless"].map({1: 1, 2: 0})

joint_df.head()

   SadOrHopeless     BMIPCT  Sad_binary
1            2.0  66.531824           0
3            1.0  98.174319           1
5            2.0  33.075531           0
6            2.0  45.688334           0
7            2.0  62.390331           0

A combined dataset is created by keeping only valid SadOrHopeless responses and non-missing BMIPCT values. This dataset will be used for additional EDA to explore the relationship between BMI percentile and the likelihood of feeling sad or hopeless.

## 11. Sample Sizes

In [23]:
print("SadOrHopeless sample size:", len(sad_df))
print("BMIPCT sample size:", len(bmi_df))
print("Joint sample size for extra EDA:", len(joint_df))

SadOrHopeless sample size: 13845
BMIPCT sample size: 13062
Joint sample size for extra EDA: 12902

After cleaning the data, we obtained the final sample sizes for both the proportion and mean analyses. These values will be used in subsequent EDA and inference steps.

## 12. Save Processed Datasets

In [24]:
sad_df.to_csv("../data/processed/sad_cleaned.csv", index=False)
bmi_df.to_csv("../data/processed/bmi_cleaned.csv", index=False)
joint_df.to_csv("../data/processed/joint_cleaned.csv", index=False)

The cleaned datasets are saved in the processed folder. This ensures that the data cleaning steps are reproducible and that the analysis can be performed consistently using the processed data.